[package]
name = "uefi_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { version = "0.16.0", features = ["exts", "alloc", "logger"] }
uefi-services = "0.13.0"
log = "0.4.17"